DROP TABLE IF EXISTS property;
DROP TABLE IF EXISTS headervalue;
DROP TABLE IF EXISTS header;
DROP TABLE IF EXISTS multipart;
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS pop_uidl;
DROP TABLE IF EXISTS accountitem;
DROP TABLE IF EXISTS walletitem;
